context:
  version: 0.13.0

package:
  name: ddh
  version: ${{ version }}

source:
  url: https://github.com/darakian/ddh/archive/${{ version }}.tar.gz
  sha256: 87010f845fa68945d2def4a05a3eb796222b67c5d3cea41e576cfaf2ab078ef8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - ddh --help

about:
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fast duplicate file finder
  homepage: https://github.com/darakian/ddh
  repository: https://github.com/darakian/ddh

extra:
  recipe-maintainers:
    - danielnachun
